### ISSUE TITLE
CDS phase checkup: "ValueError: Unknown format code 'd' for object of type 'str'"

### ISSUE THREAD

**Issue by estolle** [hotdogee/gff3-py#6]
Hi there, 
I just discovered your nice gff3 tool during my search for a tool adding the phase to the CDS's in a gff file ( (phases are missing for all CDS, I have the corresponding genomic.fa from an insect). However, I have troubles with checking the phase of the CDS as it throws an error about unknown format code. Do you have any idea how to mitigate this? Any help would be greatly appreciated!

my command
python /opt/scripts/gff_fix.py --gff_file edit.1.0.annotations.formatted.gff --fasta_file Edil.fa --allowed_num_of_n 0 --check_n_feature_types CDS --report_file Edil.1.0.gff.validation_report.txt

output:
INFO     Checking GFF3 file (edit.1.0.annotations.formatted.gff)...
INFO     Checking syntax and formatting...
INFO     Checking reference seqid, bounds and N count...
INFO     Checking parent boundaries...
Traceback (most recent call last):
  File "/opt/scripts/gff_fix.py", line 139, in <module>
    gff3.check_phase()
  File "/usr/local/lib/python2.7/dist-packages/gff3/gff3.py", line 213, in check_phase
    self.add_line_error(line, {'message': 'Wrong phase {0:d}, should be {1:d}'.format(line['phase'], phase), 'error_type': 'PHASE'})
ValueError: Unknown format code 'd' for object of type 'str'

**Comment by hsiaoyi0504** [comment]
Hi @estolle, sorry for the late response, but it seems to me you may want to post https://github.com/NAL-i5K/GFF3toolkit/ rather than this project.

**Comment by hsiaoyi0504** [comment]
To make us to help you easier, can you also provide the version inforamtion gff3, gff3tool you use and the input file that raises this error ?
